# Array slicing examples

In [1]:
import numpy as np

In [2]:
xvec = np.arange(0,12,1)
xvec

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Slicing in Python is about picking off parts of an array.  For `xvec`, we can use `xvec[`*start*`:`*stop*`:`*skip*`]` where leaving out one or more of *start*, *stop*, *skip$ means we get everything.  Examples:

In [8]:
print(xvec[::2])   # all even elements

print(xvec[0::2])  # could specify the starting elements also

[ 0  2  4  6  8 10]
[ 0  2  4  6  8 10]


In [4]:
xvec[1::2]  # all odd elements

array([ 1,  3,  5,  7,  9, 11])

In [5]:
print(xvec[:])  # all elements

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [6]:
# every fourth element, starting at 0, then 1, then 2, then 3
print(xvec[::4], 
      xvec[1::4],
      xvec[2::4],
      xvec[3::4]) 

[0 4 8] [1 5 9] [ 2  6 10] [ 3  7 11]
